name: Update Playlist

on:
  schedule:
    # 日曜日の17:00 JST（UTC 8:00）に実行
    - cron: '0 8 * * 0'
  workflow_dispatch: # 手動実行も可能

jobs:
  update-playlist:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1.3
        bundler-cache: true
    
    - name: Setup database
      run: |
        bundle exec rails db:create
        bundle exec rails db:migrate
      env:
        DATABASE_URL: postgres://postgres:postgres@localhost:5432/test
    
    - name: Update playlist
      run: bundle exec rails playlist:update
      env:
        CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
        PLAYLIST_ID: ${{ secrets.SPOTIFY_PLAYLIST_ID }}
        SPOTIFY_REFRESH_TOKEN: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}
        SPOTIFY_USER_ID: ${{ secrets.SPOTIFY_USER_ID }}
        DATABASE_URL: postgres://postgres:postgres@localhost:5432/test
    
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5