name: Update Playlist

on:
  schedule:
    # 日曜日の16:00 JST（UTC 7:00）に実行
    - cron: '0 7 * * 0'
  workflow_dispatch: # 手動実行も可能

jobs:
  update-playlist:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1.3
        bundler-cache: false  # キャッシュを無効化
    
    - name: Bundle install
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
    
    - name: Setup database
      run: |
        bundle exec rails db:setup
      env:
        RAILS_ENV: test
        DATABASE_URL: sqlite3:db/test.sqlite3
    
    - name: Update playlist
      run: bundle exec rails playlist:update
      env:
        CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
        PLAYLIST_ID: ${{ secrets.SPOTIFY_PLAYLIST_ID }}
        SPOTIFY_REFRESH_TOKEN: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}
        SPOTIFY_USER_ID: ${{ secrets.SPOTIFY_USER_ID }}
        RAILS_ENV: test
        DATABASE_URL: sqlite3:db/test.sqlite3